name: paraulogic

on:
  workflow_dispatch:
    inputs:
      mandatory_char:
        description: 'Mandatory character'
        required: true
        default: 'n'
      optional_chars:
        description: 'Optional characters'
        required: true
        default: 'ceortu'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      INPUT_MANDATORY_CHAR: ${{ github.event.inputs.mandatory_char }}
      INPUT_OPTIONAL_CHARS: ${{ github.event.inputs.optional_chars }}
    outputs:
      mandatory_char: ${{ steps.execute.outputs.mandatory_char }}
      optional_chars: ${{ steps.execute.outputs.optional_chars }}
      result: ${{ steps.execute.outputs.result }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade unidecode
      - id: execute
        name: "Run"
        run: |
          echo "::set-output name=mandatory_char::$(echo $INPUT_MANDATORY_CHAR)";
          echo "::set-output name=optional_chars::$(echo $INPUT_OPTIONAL_CHARS)";
          python run.py ${INPUT_MANDATORY_CHAR} ${INPUT_OPTIONAL_CHARS};
          echo "::set-output name=result::$(echo $PARAULOGIC_RESULT)";